import { globby } from "globby";
import handlebars from "handlebars";

import { getShowcaseConfig } from "./utils.mjs";

interface StoryPathsObject {
  [storyId: string]: {
    path: string;
    esmPath: string;
  };
}

export const getStoryComponentPaths = async (): Promise<StoryPathsObject> => {
  const config = await getShowcaseConfig();
  const paths = await globby(
    config?.stories || ["src/**/*.stories.{js,jsx,ts,tsx}"],
  );
  let pathsObject: StoryPathsObject = {};
  paths.forEach((path) => {
    const id = path.split("/").slice(-1)[0].split(".")[0];
    if (pathsObject[id]) {
      throw new Error(`Duplicate story file name found: ${path}`);
    }
    // esm path is the regular path but with .js extension
    pathsObject[id] = {
      path,
      esmPath: path.replace(/\.[^/.]+$/, ".js"),
    };
  });
  return pathsObject;
};

export const createCompileTarget = async (storyPaths: StoryPathsObject) => {
  const imports = Object.keys(storyPaths).map((componentName) => ({
    name: componentName,
    path: "@showcasejs/internal/root/" + storyPaths[componentName].path,
  }));
  const componentNames = Object.keys(storyPaths).map((storyId) => storyId);
  let template = `// the following is auto-generated by Showcase.js on {{ timestamp }}
{{#each imports}}
import * as {{ this.name }} from "{{ this.path }}";
{{/each}}
export const stories = { {{ componentNames }} };
`;
  const mainPaths = await globby(".showcase/main.{tsx,ts,jsx,js}");
  if (mainPaths.length > 0) {
    template += `export * as main from '@showcasejs/internal/root/${mainPaths[0]}';\n`;
  } else {
    template += "export const main = undefined;\n";
  }
  const previewPaths = await globby(".showcase/preview.{tsx,ts,jsx,js}");
  if (previewPaths.length > 0) {
    template += `export * as preview from '@showcasejs/internal/root/${previewPaths[0]}';\n`;
  } else {
    template += "export const preview = undefined;\n";
  }
  const compiler = handlebars.compile(template);
  const compiled = compiler({
    timestamp: new Date().toISOString(),
    imports,
    componentNames,
  });
  return compiled;
};
